spring:
  application:
    name: order-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8082/realms/shopper}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8082/realms/shopper/protocol/openid-connect/certs}
          audiences: ${JWT_AUDIENCE:order-service}

  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:order-service}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: by.innowise.orderservice.event
        spring.json.value.default.type: by.innowise.orderservice.event.PaymentEvent
        spring.json.use.type.headers: false

app:
  kafka:
    payment-events-topic: ${PAYMENT_EVENTS_TOPIC:payment-events}

server:
  port: ${SERVER_PORT:8083}

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha