--liquibase formatted sql

--changeset pavel:001-create-items-table
CREATE TABLE items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_items PRIMARY KEY,
    name       VARCHAR(255)   NOT NULL,
    price      NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_items_price_non_negative
        CHECK (price >= 0)
);

--rollback DROP TABLE IF EXISTS items;


--changeset pavel:002-create-orders-table
CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_orders PRIMARY KEY,
    user_id     BIGINT         NOT NULL,
    status      VARCHAR(50)    NOT NULL,
    total_price NUMERIC(19, 2) NOT NULL DEFAULT 0,
    deleted     BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_orders_total_price_non_negative
        CHECK (total_price >= 0)
);

--rollback DROP TABLE IF EXISTS orders;


--changeset pavel:003-create-order-items-table
CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_order_items PRIMARY KEY,
    order_id   BIGINT      NOT NULL,
    item_id    BIGINT      NOT NULL,
    quantity   INTEGER     NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
            REFERENCES orders (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_order_items_item
        FOREIGN KEY (item_id)
            REFERENCES items (id),

    CONSTRAINT chk_order_items_quantity_positive
        CHECK (quantity > 0)
);

--rollback DROP TABLE IF EXISTS order_items;
